kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: python
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: productpage
  Project: user1-bookinfo
  Name: python-productpage