kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: python
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: bookinfo1
  Name: productpage
  Url:
  - Name: productpage-8080
    Port: 8080
