apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: bookinfo
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: bookinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: bookinfo
    app.kubernetes.io/part-of: bookinfo
    app.openshift.io/runtime: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo
  template:
    metadata:
      labels:
        app: bookinfo
        version: v1
        app.openshift.io/runtime: java
    spec:
      containers:
      - name: reviews
        image: quay.io/jdob/bookinfo-reviews:1.1
        ports:
        - containerPort: 9080
